Users/urls.py
from django.urls import path  
from Users import views
from django.conf.urls.static import static 
from django.conf import settings 

app_name = 'Users'
urlpatterns = [   
    path('', views.user_index,name='user_index'),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
    path('adminlogin/',views.Adminlogin,name='adminlogin')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iboard/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import dashboard
from django.contrib.auth import views as auth_views
from Users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('dashboard/',dashboard,name='dashboard'),
    path('usermaster/',include(('usermaster.urls','url'), namespace='url')),
    path('users/',include(('Users.urls','url'), namespace='user_index')),
    path('register/',user_views.register,name='register'),
    path('',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

usermaster/urls.py
from usermaster import views
from django.urls import path


app_name = 'usermaster' 

urlpatterns = [
    path('',views.home,name='home'),
    path('machine_master/',views.index,name='index'),  
    path('addnew',views.addnew),  
    path('edit/<int:id>',views.edit),  
    path('update/<int:id>',views.update),  
    path('delete/<int:id>',views.destroy),
    path('image_view/',views.images_view,name='images_view'),
    #Control
    path('controlfile/',views.control_index,name='control_index'),
    path('cdelete/<int:id>',views.control_destroy,name='control_destroy'),
    path('controlupload/',views.control_upload,name='control_upload'),
    path('upload/',views.upload,name='upload'),
    path('save',views.save_machine,name='save_machine'),
    #Process
    path('processfile/',views.process_index,name='process_index'),
    path('pdelete/<int:id>',views.process_destroy,name='process_destroy'),
    path('processupload/',views.process_upload,name='process_upload'),
    path('pupload/',views.p_upload,name='p_upload'),
    path('psave',views.p_save_machine,name='p_save_machine'),

    #Skill Matrix
    path('skillfile/',views.skill_index,name='skill_index'),
    path('skdelete/<int:id>',views.skill_destroy,name='skill_destroy'),
    path('skillupload/',views.skill_upload,name='skill_upload'),
    path('skupload/',views.sk_upload,name='sk_upload'),
    path('sksave',views.skill_save_machine,name='skill_save_machine'),

    #Maintenance 
    path('maintainfile/',views.maintain_index,name='maintain_index'),
    path('mdelete/<int:id>',views.maintain_destroy,name='maintain_destroy'),
    path('maintainupload/',views.maintain_upload,name='maintain_upload'),
    path('mupload/',views.m_upload,name='m_upload'),
    path('msave',views.maintain_save_machine,name='maintain_save_machine'),

    #SWS
    path('swsfile/',views.sws_index,name='sws_index'),
    path('swdelete/<int:id>',views.sws_destroy,name='sws_destroy'),
    path('swsupload/',views.sws_upload,name='sws_upload'),
    path('swupload/',views.sw_upload,name='sw_upload'),
    path('swsave',views.sws_save_machine,name='sws_save_machine'),

    #Safety
    path('safetyfile/',views.safety_index,name='safety_index'),
    path('sfdelete/<int:id>',views.safety_destroy,name='safety_destroy'),
    path('safetyupload/',views.safety_upload,name='safety_upload'),
    path('sfupload/',views.sf_upload,name='sf_upload'),
    path('sfsave',views.safety_save_machine,name='safety_save_machine'),

    #PFD
    path('pfdfile/',views.pfd_index,name='pfd_index'),
    path('pfdelete/<int:id>',views.pfd_destroy,name='pfd_destroy'),
    path('pfdupload/',views.pfd_upload,name='pfd_upload'),
    path('pfupload/',views.pf_upload,name='pf_upload'),
    path('pfsave',views.pfd_save_machine,name='pfd_save_machine'),

    #Gauges
    path('gaugesfile/',views.gauges_index,name='gauges_index'),
    path('gdelete/<int:id>',views.gauges_destroy,name='gauges_destroy'),
    path('gaugesupload/',views.gauges_upload,name='gauges_upload'),
    path('gaugeupload/',views.gauge_upload,name='gauge_upload'),
    path('gsave',views.gauges_save_machine,name='gauges_save_machine'),

    #video
    path('videos/',views.showvideo,name='showvideo'),
    path('video/',views.viewvideo,name='viewvideo'),
    path('vdelete/<int:id>',views.videos_destroy,name='videos_destroy'),

]

usermaster/views.py
from django.http.response import HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import redirect, render
from usermaster.forms import MachineForm, ControlForm, ProcessForm, SkillForm, MaintainForm, SwsForm, SafetyForm, PfdForm, GaugesForm, VideoForm
from usermaster.models import Machine, Controlmachine, Processmachine, Skillmachine, Maintainmachine, Swsmachine, Safetymachine, Pfdmachine, Gaugesmachine, Video
# Create your views here.

def home(request):
    return render(request,'usermaster/home.html')

def addnew(request):  
    if request.method == "POST":  
        form = MachineForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return HttpResponseRedirect('/usermaster/machine_master/')  
            except:  
                pass 
    else:  
        form = MachineForm()  
    return render(request,'usermaster/index.html',{'form':form})  

def index(request):  
    machines = Machine.objects.all()  
    return render(request,"usermaster/show.html",{'machines':machines}) 

def edit(request, id):  
    machine = Machine.objects.get(id=id)  
    return render(request,'usermaster/edit.html',{'machine':machine})

def update(request, id):  
    machine = Machine.objects.get(id=id)  
    form = MachineForm(request.POST,instance=machine)  
    if form.is_valid():  
        form.save()  
        return HttpResponseRedirect('/usermaster/machine_master/')  
    return render(request,'usermaster/edit.html',{'machine': machine})

def destroy(request, id):  
    machine = Machine.objects.get(id=id)  
    machine.delete()  
    return HttpResponseRedirect("/usermaster/machine_master/") 

def images_view(request):
    return render(request,'usermaster/image.html')

#Control Process
def control_upload(request):  
    if request.method == 'POST':
        form = ControlForm(request.POST, request.FILES)  
        if form.is_valid():
            model_instance = form.save()
            model_instance.save()
            messages.success(request, 'File Uploaded')
    else:
        form = ControlForm()
    controlmachines = Controlmachine.objects.all()
    return render(request,'usermaster/control_uploadfile.html',{'form':form,'controlmachines':controlmachines})

def control_index(request):  
    controlmachines = Controlmachine.objects.all()  
    return render(request,"usermaster/control_show.html",{'controlmachines':controlmachines}) 

def control_destroy(request, id):
    controlmachines = Controlmachine.objects.get(id=id)  
    controlmachines.delete()  
    return HttpResponseRedirect('/usermaster/controlfile/')

def upload(request):
    controlmachines = Controlmachine.objects.all()
    return render(request,'usermaster/upload.html',{'controlmachines':controlmachines})

def save_machine(request):
   if request.method == "POST":
      machine_name = request.POST.get('machinename', '')
      operation_no = request.POST.get('operationname','')
      choiced_cmachine = Controlmachine.objects.filter(machine_name=machine_name, operation_no=operation_no)
      controlmachines = Controlmachine.objects.all()
      return render(request,'usermaster/upload.html',{'controlmachines':controlmachines,'choiced_cmachine':choiced_cmachine})

#Process Sheet
def process_upload(request):  
    if request.method == 'POST':
        form = ProcessForm(request.POST, request.FILES)  
        if form.is_valid():
            model_instance = form.save()
            model_instance.save()
            messages.success(request, 'File Uploaded')
    else:
        form = ProcessForm()
    processmachiness = Processmachine.objects.all()
    return render(request,'usermaster/process_uploadfile.html',{'form':form,'processmachiness':processmachiness})

def process_index(request):  
    processmachines = Processmachine.objects.all()  
    return render(request,"usermaster/process_show.html",{'processmachines':processmachines}) 

def process_destroy(request, id):  
    processmachines = Processmachine.objects.get(id=id)  
    processmachines.delete()  
    return HttpResponseRedirect('/usermaster/processfile/')

def p_upload(request):
    pmachines = Processmachine.objects.all()
    return render(request,'usermaster/p_upload.html',{'pmachines':pmachines})

def p_save_machine(request):
   if request.method == "POST":
      machine_name = request.POST.get('machinename', '')
      operation_no = request.POST.get('operationname','')
      choiced_pmachine = Processmachine.objects.filter(machine_name=machine_name, operation_no=operation_no)
      pmachines = Processmachine.objects.all()
      return render(request,'usermaster/p_upload.html',{'pmachines':pmachines,'choiced_pmachine':choiced_pmachine})

#Skill Matrix
def skill_upload(request):  
    if request.method == 'POST':
        form = SkillForm(request.POST, request.FILES)  
        if form.is_valid():
            model_instance = form.save()
            model_instance.save()
            messages.success(request, 'File Uploaded')
    else:
        form = SkillForm()
    skillmachiness = Skillmachine.objects.all()
    return render(request,'usermaster/skill_uploadfile.html',{'form':form,'skillmachiness':skillmachiness})

def skill_index(request):  
    skillmachines = Skillmachine.objects.all()  
    return render(request,"usermaster/skill_show.html",{'skillmachines':skillmachines}) 

def skill_destroy(request, id):  
    skillmachines = Skillmachine.objects.get(id=id)  
    skillmachines.delete()  
    return HttpResponseRedirect('/usermaster/skillfile/')

def sk_upload(request):
    skillmachines = Skillmachine.objects.all()
    return render(request,'usermaster/skill_upload.html',{'skillmachines':skillmachines})

def skill_save_machine(request):
   if request.method == "POST":
      machine_name = request.POST.get('machinename', '')
      operation_no = request.POST.get('operationname','')
      choiced_skillmachine = Skillmachine.objects.filter(machine_name=machine_name, operation_no=operation_no)
      skillmachines = Skillmachine.objects.all()
      return render(request,'usermaster/skill_upload.html',{'skillmachines':skillmachines,'choiced_skillmachine':choiced_skillmachine})

#Maintenance
def maintain_upload(request):  
    if request.method == 'POST':
        form = MaintainForm(request.POST, request.FILES)  
        if form.is_valid():
            model_instance = form.save()
            model_instance.save()
            messages.success(request, 'File Uploaded')
    else:
        form = MaintainForm()
    maintainmachiness = Maintainmachine.objects.all()
    return render(request,'usermaster/maintain_uploadfile.html',{'form':form,'maintainmachiness':maintainmachiness})

def maintain_index(request):  
    maintainmachines = Maintainmachine.objects.all()  
    return render(request,"usermaster/maintain_show.html",{'maintainmachines':maintainmachines}) 

def maintain_destroy(request, id):  
    maintainmachines = Maintainmachine.objects.get(id=id)  
    maintainmachines.delete()  
    return HttpResponseRedirect('/usermaster/maintainfile/')

def m_upload(request):
    maintainmachines = Maintainmachine.objects.all()
    return render(request,'usermaster/m_upload.html',{'maintainmachines':maintainmachines})

def maintain_save_machine(request):
   if request.method == "POST":
      machine_name = request.POST.get('machinename', '')
      operation_no = request.POST.get('operationname','')
      choiced_maintainmachine = Maintainmachine.objects.filter(machine_name=machine_name, operation_no=operation_no)
      maintainmachines = Maintainmachine.objects.all()
      return render(request,'usermaster/m_upload.html',{'maintainmachines':maintainmachines,'choiced_maintainmachine':choiced_maintainmachine})

#SWS
def sws_upload(request):  
    if request.method == 'POST':
        form = SwsForm(request.POST, request.FILES)  
        if form.is_valid():
            model_instance = form.save()
            model_instance.save()
            messages.success(request, 'File Uploaded')
    else:
        form = SwsForm()
    swsmachiness = Swsmachine.objects.all()
    return render(request,'usermaster/sws_uploadfile.html',{'form':form,'swsmachiness':swsmachiness})

def sws_index(request):  
    swsmachines = Swsmachine.objects.all()  
    return render(request,"usermaster/sws_show.html",{'swsmachines':swsmachines}) 

def sws_destroy(request, id):  
    swsmachines = Swsmachine.objects.get(id=id)  
    swsmachines.delete()  
    return HttpResponseRedirect('/usermaster/swsfile/')

def sw_upload(request):
    swsmachines = Swsmachine.objects.all()
    return render(request,'usermaster/sw_upload.html',{'swsmachines':swsmachines})

def sws_save_machine(request):
   if request.method == "POST":
      machine_name = request.POST.get('machinename', '')
      operation_no = request.POST.get('operationname','')
      choiced_swsmachine = Swsmachine.objects.filter(machine_name=machine_name, operation_no=operation_no)
      swsmachines = Swsmachine.objects.all()
      return render(request,'usermaster/sw_upload.html',{'swsmachines':swsmachines,'choiced_swsmachine':choiced_swsmachine})


#Safety
def safety_upload(request):  
    if request.method == 'POST':
        form = SafetyForm(request.POST, request.FILES)  
        if form.is_valid():
            model_instance = form.save()
            model_instance.save()
            messages.success(request, 'File Uploaded')
    else:
        form = SafetyForm()
    safetymachiness = Safetymachine.objects.all()
    return render(request,'usermaster/safety_uploadfile.html',{'form':form,'safetymachiness':safetymachiness})

def safety_index(request):  
    safetymachines = Safetymachine.objects.all()  
    return render(request,"usermaster/safety_show.html",{'safetymachines':safetymachines}) 

def safety_destroy(request, id):  
    safetymachines = Safetymachine.objects.get(id=id)  
    safetymachines.delete()  
    return HttpResponseRedirect('/usermaster/safetyfile/')

def sf_upload(request):

usermaster/templates/usermaster_base/footer.html
<footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                © {% now "Y" %}Ashok Iron Works. All Rights Reserved
            </div>
            <div class="col-sm-6 text-right">
                Developed by <a href="#">Manoj Tolagekar</a>
            </div>
        </div>
    </div>
</footer>

usermaster/templates/usermaster_base/navbar.html
{% load static %}

<header id="header" class="header" style="background: black">
    <div class="top-left">
        <div class="navbar-header" style="background: black">
            <a class="navbar-brand" style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ASHOK IRON WORKS</a>

            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div style="position: fixed; margin-top: 15px;">
        <img src="https://raw.githubusercontent.com/manoj5078/images2/main/logo.jpg" alt="logo">
    </div>
    <div>
        <h3 style="position: absolute; margin-left: 400px; margin-bottom: 5px; color: white;">MASTER</h3>
    </div>
    <div>
        <p style="margin-top: 10px; margin-left: 900px; position: relative;">{% now 'D' %} {% now 'H:m:s' %} {% now "d-M-Y" %}</p>
    </div>
</header>

usermaster/templates/usermaster_base/sidebar.html
<aside id="left-panel" class="left-panel" style="background: black">
    <nav class="navbar navbar-expand-sm navbar-default" style="background: black">
        <div id="main-menu" class="main-menu collapse navbar-collapse" style="background: black">
            <ul class="nav navbar-nav">
                <li class="active" style="background: black" >
                    <a href="{% url 'usermaster:home' %}"><i class="menu-icon fa fa-laptop"></i>HOME</a>
                </li>
                <li class="menu-title" style="color: white">i - BOARD S3 LINE</li><!-- /.menu-title -->
                <li class="menu-item-has-children dropdown" >
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Control Process</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:control_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:control_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Process Sheet</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:process_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:process_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Skill Matrix</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:skill_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:skill_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Maintenance</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:maintain_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:maintain_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Sws</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:sws_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:sws_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Safety</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:safety_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:safety_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>PFD</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:pfd_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:pfd_index' %}">View Files</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-file"></i>Gauges</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="{% url 'usermaster:gauges_upload' %}">Add File</a></li>
                        <li><i class="fa fa-eye" style="color: darkblue"></i><a href="{% url 'usermaster:gauges_index' %}">View Files</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="{% url 'usermaster:index' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>Machine Master</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="{% url 'Users:user_index' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Users</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="{% url 'usermaster:showvideo' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-camera"></i>Videos</a>
                </li>
                <li class="menu-item-has-children">
                    <a href="{% url 'logout' %}" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-logout"></i>Logout</a>
                </li>
                <li class="menu-item-has-children">
                    <a href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-logout"></i>Logout</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>