Users/urls.py
from django.urls import path  
from Users import views
from django.conf.urls.static import static 
from django.conf import settings 

app_name = 'Users'
urlpatterns = [   
    path('', views.user_index,name='user_index'),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
    path('adminlogin/',views.Adminlogin,name='adminlogin')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iboard/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import dashboard
from django.contrib.auth import views as auth_views
from Users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('dashboard/',dashboard,name='dashboard'),
    path('usermaster/',include(('usermaster.urls','url'), namespace='url')),
    path('users/',include(('Users.urls','url'), namespace='user_index')),
    path('register/',user_views.register,name='register'),
    path('',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

usermaster/urls.py
from usermaster import views
from django.urls import path


app_name = 'usermaster' 

urlpatterns = [
    path('',views.home,name='home'),
    path('machine_master/',views.index,name='index'),  
    path('addnew',views.addnew),  
    path('edit/<int:id>',views.edit),  
    path('update/<int:id>',views.update),  
    path('delete/<int:id>',views.destroy),
    path('image_view/',views.images_view,name='images_view'),
    #Control
    path('controlfile/',views.control_index,name='control_index'),
    path('cdelete/<int:id>',views.control_destroy,name='control_destroy'),
    path('controlupload/',views.control_upload,name='control_upload'),
    path('upload/',views.upload,name='upload'),
    path('save',views.save_machine,name='save_machine'),
    #Process
    path('processfile/',views.process_index,name='process_index'),
    path('pdelete/<int:id>',views.process_destroy,name='process_destroy'),
    path('processupload/',views.process_upload,name='process_upload'),
    path('pupload/',views.p_upload,name='p_upload'),
    path('psave',views.p_save_machine,name='p_save_machine'),

    #Skill Matrix
    path('skillfile/',views.skill_index,name='skill_index'),
    path('skdelete/<int:id>',views.skill_destroy,name='skill_destroy'),
    path('skillupload/',views.skill_upload,name='skill_upload'),
    path('skupload/',views.sk_upload,name='sk_upload'),
    path('sksave',views.skill_save_machine,name='skill_save_machine'),

    #Maintenance 
    path('maintainfile/',views.maintain_index,name='maintain_index'),
    path('mdelete/<int:id>',views.maintain_destroy,name='maintain_destroy'),
    path('maintainupload/',views.maintain_upload,name='maintain_upload'),
    path('mupload/',views.m_upload,name='m_upload'),
    path('msave',views.maintain_save_machine,name='maintain_save_machine'),

    #SWS
    path('swsfile/',views.sws_index,name='sws_index'),
    path('swdelete/<int:id>',views.sws_destroy,name='sws_destroy'),
    path('swsupload/',views.sws_upload,name='sws_upload'),
    path('swupload/',views.sw_upload,name='sw_upload'),
    path('swsave',views.sws_save_machine,name='sws_save_machine'),

    #Safety
    path('safetyfile/',views.safety_index,name='safety_index'),
    path('sfdelete/<int:id>',views.safety_destroy,name='safety_destroy'),
    path('safetyupload/',views.safety_upload,name='safety_upload'),
    path('sfupload/',views.sf_upload,name='sf_upload'),
    path('sfsave',views.safety_save_machine,name='safety_save_machine'),

    #PFD
    path('pfdfile/',views.pfd_index,name='pfd_index'),
    path('pfdelete/<int:id>',views.pfd_destroy,name='pfd_destroy'),
    path('pfdupload/',views.pfd_upload,name='pfd_upload'),
    path('pfupload/',views.pf_upload,name='pf_upload'),
    path('pfsave',views.pfd_save_machine,name='pfd_save_machine'),

    #Gauges
    path('gaugesfile/',views.gauges_index,name='gauges_index'),
    path('gdelete/<int:id>',views.gauges_destroy,name='gauges_destroy'),
    path('gaugesupload/',views.gauges_upload,name='gauges_upload'),
    path('gaugeupload/',views.gauge_upload,name='gauge_upload'),
    path('gsave',views.gauges_save_machine,name='gauges_save_machine'),

    #video
    path('videos/',views.showvideo,name='showvideo'),
    path('video/',views.viewvideo,name='viewvideo'),
    path('vdelete/<int:id>',views.videos_destroy,name='videos_destroy'),

]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>
      {% block title %}
      {% endblock title %}
  </title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static '/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static '/modules/jqvmap/dist/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/weather-icon/css/weather-icons.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/weather-icon/css/weather-icons-wind.min.css' %}">
  <link rel="stylesheet" href="{% static '/modules/summernote/summernote-bs4.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static '/css/style.css' %}">
  <link rel="stylesheet" href="{% static '/css/components.css' %}">

  {% block custom_css %}
  {% endblock custom_css %}

  <style>
  ul.errorlist{
    margin:0px;
  }
  .no-margin{
    margin:0px;
  }
  </style>
<!-- /END GA --></head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      {% include 'base/navbar.html' %}
      {% include 'base/sidebar.html' with id=form.instance.id %}
   

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <!-- <h1>{% block page_title %}{% endblock page_title %}</h1> -->
          </div>
        {% block content %}
        {% endblock content %}
      </div>
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; {% now "Y" %} <div class="bullet"></div>  By Manoj Tolagekar 
        </div>
        <div class="footer-right">
          
        </div>
      </footer>
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="{% static '/modules/jquery.min.js' %}"></script>
  <script src="{% static '/modules/popper.js' %}"></script>
  <script src="{% static '/modules/tooltip.js' %}"></script>
  <script src="{% static '/modules/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static '/modules/moment.min.js' %}"></script>
  <script src="{% static '/js/stisla.js' %}"></script>
  
  <!-- JS Libraies -->
  <script src="{% static '/modules/simple-weather/jquery.simpleWeather.min.js' %}"></script>
  <script src="{% static '/modules/chart.min.js' %}"></script>
  <script src="{% static '/modules/jqvmap/dist/jquery.vmap.min.js' %}"></script>
  <script src="{% static '/modules/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
  <script src="{% static '/modules/summernote/summernote-bs4.js' %}"></script>
  <script src="{% static '/modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static '/js/page/index-0.js' %}"></script>
  
  <!-- Template JS File -->
  <script src="{% static '/js/scripts.js' %}"></script>
  <script src="{% static '/js/custom.js' %}"></script>
  {% block custom_js %}
  {% endblock custom_js %}
  <script>
    document.getElementById("title").onkeyup=function(){
      document.getElementById("url_slug").value=document.getElementById("title").value.toLowerCase().replaceAll(" ","-");
    }
  </script>
</body>
</html>

templates/base/navbar.html
{% load static %}
<div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
          <div class="search-element">
           
          </div>
        </form>
        <ul class="navbar-nav navbar-right">
    
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{% static '/img/avatar/avatar-1.png' %}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hi, {{ request.user.username }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-title">Logged in a min ago</div>
              <a href="" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Admin
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'logout' %}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>

templates/base/sidebar.html
{% load static %}
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="/"><img src="{% static '/img/logo.jpg' %}" style="height: 85px;" /></a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="/"><img src="{% static '/img/logo.jpg' %}" style="height: 85px;" /></a>
      </div>
      <ul class="sidebar-menu">
        <li class="menu-header">iboard S3-Line Dashboard</li>
        <!-- {% comment %} CATEGORY MENU {% endcomment %} -->
        <!-- {% url 'category_list' as category_list %}
        {% url 'category_create' as category_create %}
        {% url 'category_update' id as category_update %} -->
        <li class="dropdown">
          <a href="{% url 'usermaster:upload' %}"><i class="fas fa-dice-d6"></i><span>Control Process</span></a>
        </li>


        <!-- {% comment %} SUB CATEGORY MENU {% endcomment %}
        {% url 'sub_category_list' as sub_category_list %}
        {% url 'sub_category_create' as sub_category_create %}
        {% url 'sub_category_update' id as sub_category_update %} -->
        <li class="dropdown">
          <a href="{% url 'usermaster:p_upload' %}"><i class="fas fa-dice-d6"></i><span>Process Sheet</span></a>
        </li>

        
        <!-- {% comment %} Merchant User MENU {% endcomment %}
        {% url 'merchant_create' as merchant_create %}
        {% url 'merchant_list' as merchant_list %}
        {% url 'merchant_update' id as merchant_update %} -->
        <li class="dropdown">
          <a href="{% url 'usermaster:sk_upload' %}"><i class="fas fa-dice-d6"></i><span>Skill Matrix</span></a>
        </li>  
        <!-- {% comment %} STAFF USER URLS {% endcomment %}
        {% url 'staff_create' as staff_create %}
        {% url 'staff_list' as staff_list %}
        {% url 'staff_update' id as staff_update %} -->
        <li class="dropdown">
          <a href="{% url 'usermaster:m_upload' %}"><i class="fas fa-dice-d6"></i><span>Maintenance</span></a>
        </li>      
        <!-- {% comment %} CUSTOMER USER URLS {% endcomment %}
        {% url 'customer_create' as customer_create %}
        {% url 'customer_list' as customer_list %}
        {% url 'customer_update' id as customer_update %} -->
        <li class="dropdown">
          <a href="{% url 'usermaster:sw_upload' %}"><i class="fas fa-dice-d6"></i><span>Sws</span></a>
        </li>      
       
       <!-- {% url 'product_view' as product_view %}
       {% url 'product_list' as product_list %}
       {% url 'product_edit' product.id as product_edit %}
       {% url 'product_add_media' product.id as product_add_media %}
       {% url 'product_edit_media' product.id as product_edit_media %}
       {% url 'product_add_stocks' product.id as product_add_stocks %} -->
        <li class="dropdown">
          <a href="{% url 'usermaster:sf_upload' %}"><i class="fas fa-dice-d6"></i><span>Safety</span></a>
        </li>

        <li class="dropdown">
          <a href="{% url 'usermaster:pf_upload' %}"><i class="fas fa-dice-d6"></i><span>PFD</span></a>
        </li>

        <li class="dropdown">
          <a href="{% url 'usermaster:gauge_upload' %}"><i class="fas fa-dice-d6"></i><span>Gauges</span></a>
        </li>

        <li class="dropdown">
          <a href="{% url 'usermaster:viewvideo' %}"><i class="fas fa-dice-d6"></i><span>Videos</span></a>
        </li>

      </ul>

      <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
        <a href="{% url 'logout' %}" class="btn btn-primary btn-lg btn-block btn-icon-split">
          <i class="fas fa-rocket"></i> LOGOUT
        </a>
      </div>        </aside>
  </div>