Users/urls.py
from django.urls import path  
from Users import views
from django.conf.urls.static import static 
from django.conf import settings 

app_name = 'Users'
urlpatterns = [   
    path('', views.user_index,name='user_index'),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),
    path('adminlogin/',views.Adminlogin,name='adminlogin')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iboard/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import dashboard
from django.contrib.auth import views as auth_views
from Users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('dashboard/',dashboard,name='dashboard'),
    path('usermaster/',include(('usermaster.urls','url'), namespace='url')),
    path('users/',include(('Users.urls','url'), namespace='user_index')),
    path('register/',user_views.register,name='register'),
    path('',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

usermaster/urls.py
from usermaster import views
from django.urls import path


app_name = 'usermaster' 

urlpatterns = [
    path('',views.home,name='home'),
    path('machine_master/',views.index,name='index'),  
    path('addnew',views.addnew),  
    path('edit/<int:id>',views.edit),  
    path('update/<int:id>',views.update),  
    path('delete/<int:id>',views.destroy),
    path('image_view/',views.images_view,name='images_view'),
    #Control
    path('controlfile/',views.control_index,name='control_index'),
    path('cdelete/<int:id>',views.control_destroy,name='control_destroy'),
    path('controlupload/',views.control_upload,name='control_upload'),
    path('upload/',views.upload,name='upload'),
    path('save',views.save_machine,name='save_machine'),
    #Process
    path('processfile/',views.process_index,name='process_index'),
    path('pdelete/<int:id>',views.process_destroy,name='process_destroy'),
    path('processupload/',views.process_upload,name='process_upload'),
    path('pupload/',views.p_upload,name='p_upload'),
    path('psave',views.p_save_machine,name='p_save_machine'),

    #Skill Matrix
    path('skillfile/',views.skill_index,name='skill_index'),
    path('skdelete/<int:id>',views.skill_destroy,name='skill_destroy'),
    path('skillupload/',views.skill_upload,name='skill_upload'),
    path('skupload/',views.sk_upload,name='sk_upload'),
    path('sksave',views.skill_save_machine,name='skill_save_machine'),

    #Maintenance 
    path('maintainfile/',views.maintain_index,name='maintain_index'),
    path('mdelete/<int:id>',views.maintain_destroy,name='maintain_destroy'),
    path('maintainupload/',views.maintain_upload,name='maintain_upload'),
    path('mupload/',views.m_upload,name='m_upload'),
    path('msave',views.maintain_save_machine,name='maintain_save_machine'),

    #SWS
    path('swsfile/',views.sws_index,name='sws_index'),
    path('swdelete/<int:id>',views.sws_destroy,name='sws_destroy'),
    path('swsupload/',views.sws_upload,name='sws_upload'),
    path('swupload/',views.sw_upload,name='sw_upload'),
    path('swsave',views.sws_save_machine,name='sws_save_machine'),

    #Safety
    path('safetyfile/',views.safety_index,name='safety_index'),
    path('sfdelete/<int:id>',views.safety_destroy,name='safety_destroy'),
    path('safetyupload/',views.safety_upload,name='safety_upload'),
    path('sfupload/',views.sf_upload,name='sf_upload'),
    path('sfsave',views.safety_save_machine,name='safety_save_machine'),

    #PFD
    path('pfdfile/',views.pfd_index,name='pfd_index'),
    path('pfdelete/<int:id>',views.pfd_destroy,name='pfd_destroy'),
    path('pfdupload/',views.pfd_upload,name='pfd_upload'),
    path('pfupload/',views.pf_upload,name='pf_upload'),
    path('pfsave',views.pfd_save_machine,name='pfd_save_machine'),

    #Gauges
    path('gaugesfile/',views.gauges_index,name='gauges_index'),
    path('gdelete/<int:id>',views.gauges_destroy,name='gauges_destroy'),
    path('gaugesupload/',views.gauges_upload,name='gauges_upload'),
    path('gaugeupload/',views.gauge_upload,name='gauge_upload'),
    path('gsave',views.gauges_save_machine,name='gauges_save_machine'),

    #video
    path('videos/',views.showvideo,name='showvideo'),
    path('video/',views.viewvideo,name='viewvideo'),
    path('vdelete/<int:id>',views.videos_destroy,name='videos_destroy'),

]

usermaster/models.py
from os import link
from django.db import models

# Create your models here.
class Machine(models.Model):
    def __str__(self):
        return self.machine_name
    machine_name = models.CharField(max_length=100)
    operation_no = models.IntegerField()

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "machine"

#Control Model
class Controlmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    control_uploadfile = models.FileField(upload_to='control_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "controlmachine"

    def cdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.control_uploadfile.delete()
        super.delete(*args, *kwargs)

#Process Model
class Processmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    process_uploadfile = models.FileField(upload_to='process_files/')

    link1 = 'Edit'
    link2 = 'Delete'
    class Meta:  
        db_table = "processmachine"
    
    def pdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.process_uploadfile.delete()
        super.delete(*args, *kwargs)

#Skill Matrix
class Skillmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    skill_uploadfile = models.FileField(upload_to='skill_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "skillmachine"

    def skdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.skill_uploadfile.delete()
        super.delete(*args, *kwargs)

#Maintenance
class Maintainmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    maintain_uploadfile = models.FileField(upload_to='maintain_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "maintainmachine"

    def mdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.maintain_uploadfile.delete()
        super.delete(*args, *kwargs)

#SWS
class Swsmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    sws_uploadfile = models.FileField(upload_to='sws_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "swsmachine"

    def swdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.sws_uploadfile.delete()
        super.delete(*args, *kwargs)

#Safety
class Safetymachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    safety_uploadfile = models.FileField(upload_to='safety_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "safetymachine"
    
    def sfdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.safety_uploadfile.delete()
        super.delete(*args, *kwargs)

#PFD
class Pfdmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    pfd_uploadfile = models.FileField(upload_to='pfd_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "pfdmachine"

    def pfdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.pfd_uploadfile.delete()
        super.delete(*args, *kwargs)

#Gauges
class Gaugesmachine(models.Model):  
    machine_name = models.CharField(max_length=100)  
    operation_no = models.IntegerField()  
    gauges_uploadfile = models.FileField(upload_to='gauges_files/')

    link1 = 'Edit'
    link2 = 'Delete'
  
    class Meta:  
        db_table = "gaugesmachine"

    def gdelete(self, *args, **kwargs):
        self.machine_name.delete()
        self.operation_no.delete()
        self.gauges_uploadfile.delete()
        super.delete(*args, *kwargs)

class Video(models.Model):
    name= models.CharField(max_length=500)
    videofile= models.FileField(upload_to='videos/', null=True, verbose_name="")

    link1 = 'Edit'
    link2 = 'Delete'

    def __str__(self):
        return self.name + ": " + str(self.videofile)

    def vdelete(self, *args, **kwargs):
        self.name.delete()
        self.videofile.delete()
        super.delete(*args, *kwargs)

usermaster/forms.py
from django import forms  
from usermaster.models import Machine, Controlmachine, Processmachine, Skillmachine, Maintainmachine, Swsmachine, Safetymachine, Pfdmachine, Gaugesmachine, Video





class MachineForm(forms.ModelForm):  
    class Meta:  
        model = Machine 
        fields = ['machine_name','operation_no'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }),
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
      }

#Control Form
class ControlForm(forms.ModelForm):  
    class Meta:  
        model = Controlmachine 
        fields = ['machine_name', 'operation_no', 'control_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'control_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

#Process Form
class ProcessForm(forms.ModelForm):  
    class Meta:  
        model = Processmachine 
        fields = ['machine_name', 'operation_no', 'process_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'process_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

#Skill Matrix Form
class SkillForm(forms.ModelForm):  
    class Meta:  
        model = Skillmachine 
        fields = ['machine_name', 'operation_no', 'skill_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'skill_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

#Maintenance Form
class MaintainForm(forms.ModelForm):  
    class Meta:  
        model = Maintainmachine 
        fields = ['machine_name', 'operation_no', 'maintain_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'maintain_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

#SWS Form
class SwsForm(forms.ModelForm):  
    class Meta:  
        model = Swsmachine 
        fields = ['machine_name', 'operation_no', 'sws_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'sws_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

#Safety Form
class SafetyForm(forms.ModelForm):  
    class Meta:  
        model = Safetymachine 
        fields = ['machine_name', 'operation_no', 'safety_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'safety_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

#Pfd Form
class PfdForm(forms.ModelForm):  
    class Meta:  
        model = Pfdmachine 
        fields = ['machine_name', 'operation_no', 'pfd_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'pfd_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }


#Gauges Form
class GaugesForm(forms.ModelForm):  
    class Meta:  
        model = Gaugesmachine 
        fields = ['machine_name', 'operation_no', 'gauges_uploadfile'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'machine_name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'operation_no': forms.TextInput(attrs={ 'class': 'form-control' }),
            'gauges_uploadfile': forms.ClearableFileInput(attrs={ 'class': 'form-control' }),
      }

class VideoForm(forms.ModelForm):
    class Meta:
        model= Video
        fields= ["name", "videofile"]

usermaster/templates/usermaster/control_show.html
{% extends 'usermaster_base/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    

   
   
</head>
{% block content%}
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
            <table id="bootstrapdatatable" class="table table-striped table-bordered" width="90%">
                    <thead>
                        <th><input type="checkbox" id="checkall" /></th>
                        <th>ID</th>
                        <th>Machine Name</th>
                        <th>Operation Number</th>
                        <th>File</th>
                        <th>Delete</th>
                     </thead>
            <tbody>
            {% for control in controlmachines %}  
            <tr>  
             <td><input type="checkbox" class="checkthis" /></td>
             <td>{{ control.id }}</td>  
             <td>{{ control.machine_name }}</td>  
             <td>{{ control.operation_no }}</td>  
             <td>{{ control.control_uploadfile }}</td>
             <td><a href="/usermaster/cdelete/{{ control.id }}"><span placement="top" style="color:brown;" class="glyphicon glyphicon-trash"></span></a></td>  
            </tr>
            {% endfor %}  
            </tbody>
                 
            </table>
                </div>
            </div>
        </div>
    </div>
    <script>
       $(document).ready(function() {
           $('#bootstrapdatatable').DataTable({     
             "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
               "iDisplayLength": 3
              } 
           );
       } );
    </script>

</body>
{% endblock content %}
</html>

usermaster/templates/usermaster/edit.html
{% extends 'usermaster_base/base.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  <div class="col-md-12">  
 <form method="post" class="post-form" action="/usermaster/update/{{ machine.id }}">  
   {% csrf_token %}  
  <div class="container">  
 <br>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <h3>Update Details</h3>  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Machine Id:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{machine.id}}"/>  
  </div>  
   </div>  
   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Machine Name:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="machine_name" id="id_name" required maxlength="100" value="{{machine.machine_name}}" />  
  </div>  
   </div>    
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Operation Number:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="operation_no" id="id_contact" required maxlength="15" value="{{machine.operation_no}}" />  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-success btn-lg">Update</button>  
  </div>  
   </div>  
  </div>  
 </form>
 {% endblock content %}
</body>
</html>

usermaster/templates/usermaster/gauge_upload.html
{% extends 'base/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous"> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script> -->
</head>
<body>
    <form action="{% url 'usermaster:gauges_save_machine' %}" method="post">
        {% csrf_token %}
        <label for="machinename">Select Machine Name:</label>
        <select class="form-control form-control-md" name="machinename" id="machinename">
            
            {% for machine in gaugesmachines %}
            <option value="{{ machine.machine_name }}">{{ machine.machine_name }}</option>
            {% endfor %}
        </select>
        <br>
        <br>
        <label for="operationname">Select Operation Number:</label>
        <select class="form-control" id="operationname" name="operationname">
            
            {% for machine in gaugesmachines %}
            <option value="{{ machine.operation_no }}">{{ machine.operation_no }}</option>
            {% endfor %}
            </select>
        <br>
        <br>
        <br>
        <input class="btn btn-info" type="submit" value="Submit">
    </form>
    <br>
    <br>
    <table class="table table-bordered table-dark width=50%">
        <thead>
          <tr>
            <th scope="col">Machine Name</th>
            <th scope="col">Operation Number</th>
            <th scope="col">File 1</th>
            <th scope="col">Machine Name</th>
            <th scope="col">Operation Number</th>
            <th scope="col">File 2</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                {% for choice in choiced_gaugesmachine %}
                <td>{{choice.machine_name}}</td>
                <td>{{choice.operation_no}}</td>
                <td>
                    {% for file in gaugesmachines %}
                        {% if file == choice and file == choice %}
                        <a class="btn btn-info" href="/media/{{file.gauges_uploadfile}}">view file</a>
                        {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
        </tbody>
      </table>
    
      <script>
        function myrefresh() {
        window.location.autoreload();
    }
    myrefresh()
    </script>

</body>
</html>
{% endblock content %}

usermaster/templates/usermaster/m_upload.html
{% extends 'base/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous"> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script> -->
</head>
<body>
    <form action="{% url 'usermaster:maintain_save_machine' %}" method="post">
        {% csrf_token %}
        <label for="machinename">Select Machine Name:</label>
        <select class="form-control form-control-md" name="machinename" id="machinename">
            
            {% for machine in maintainmachines %}
            <option value="{{ machine.machine_name }}">{{ machine.machine_name }}</option>
            {% endfor %}
        </select>
        <br>
        <br>
        <label for="operationname">Select Operation Number:</label>
        <select class="form-control" id="operationname" name="operationname">
            
            {% for machine in maintainmachines %}
            <option value="{{ machine.operation_no }}">{{ machine.operation_no }}</option>
            {% endfor %}
            </select>
        <br>
        <br>
        <br>
        <input class="btn btn-info" type="submit" value="Submit">
    </form>
    <br>
    <br>
    <table class="table table-bordered table-dark width=50%">
        <thead>
          <tr>
            <th scope="col">Machine Name</th>
            <th scope="col">Operation Number</th>
            <th scope="col">File</th>
            <th scope="col">Machine Name</th>
            <th scope="col">Operation Number</th>
            <th scope="col">File2</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                {% for choice in choiced_maintainmachine %}
                <td>{{choice.machine_name}}</td>
                <td>{{choice.operation_no}}</td>
                <td>
                    {% for file in maintainmachines %}
                        {% if file == choice and file == choice %}
                        <a class="btn btn-info" href="/media/{{file.maintain_uploadfile}}">view file</a>
                        {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
        </tbody>
      </table>


</body>
</html>
{% endblock content %}

usermaster/templates/usermaster/p_upload.html
{% extends 'base/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous"> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script> -->
</head>
<body>
    <form action="{% url 'usermaster:p_save_machine' %}" method="post">
        {% csrf_token %}
        <label for="machinename">Select Machine Name:</label>
        <select class="form-control form-control-md" name="machinename" id="machinename">
            
            {% for machine in pmachines %}
            <option value="{{ machine.machine_name }}">{{ machine.machine_name }}</option>
            {% endfor %}
        </select>
        <br>
        <br>
        <label for="operationname">Select Operation Number:</label>
        <select class="form-control" id="operationname" name="operationname">
            
            {% for machine in pmachines %}
            <option value="{{ machine.operation_no }}">{{ machine.operation_no }}</option>
            {% endfor %}
            </select>
        <br>
        <br>
        <br>
        <input class="btn btn-info" type="submit" value="Submit">
    </form>
    <br>
    <br>
    <table class="table table-bordered table-dark width=50%">
        <thead>
          <tr>
            <th scope="col">Machine Name</th>
            <th scope="col">Operation Number</th>
            <th scope="col">File 1</th>
            <th scope="col">Machine Name</th>
            <th scope="col">Operation Number</th>
            <th scope="col">File 2</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                {% for choice in choiced_pmachine %}
                <td>{{choice.machine_name}}</td>
                <td>{{choice.operation_no}}</td>
                <td>
                    {% for file in pmachines %}
                        {% if file == choice and file == choice %}
                        <a class="btn btn-info" href="/media/{{file.process_uploadfile}}">view file</a>
                        {% endif %}
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
        </tbody>
      </table>

</html>
{% endblock content %}